spring:
  application:
    name: nexus-shopping
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nexus_shopping}
    username: ${DB_USERNAME:nexus}
    password: ${DB_PASSWORD:nexus}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  flyway:
    enabled: true
    placeholders:
      productSeedCount: ${PRODUCT_SEED_COUNT:1000}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  logback:
    format: ecs
    structured-logging:
      enabled: true

management:
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.flywaydb: INFO
  pattern:
    level: "%5p"
  charset:
    console: UTF-8

nexus:
  cache:
    product:
      ttl: 10m
      search-ttl: 30s
      default-ttl: 10m
    redis:
      enabled: true
