CREATE TABLE payment_provider_dispatches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_dispatch_key VARCHAR(255) NOT NULL,
    reference_id VARCHAR(255) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(32) NOT NULL,
    provider_transaction_id VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_provider_dispatches_amount_check CHECK (amount >= 0),
    CONSTRAINT uq_payment_provider_dispatches_dispatch_key UNIQUE (provider_dispatch_key)
);
