CREATE TABLE notification_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_key VARCHAR(255) NOT NULL,
    status VARCHAR(16) NOT NULL,
    order_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    attempt_reference VARCHAR(255) NOT NULL,
    recipient_email VARCHAR(254) NOT NULL,
    reference_id VARCHAR(255) NOT NULL,
    subject VARCHAR(180) NOT NULL,
    body VARCHAR(2000) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(2000),
    notification_id VARCHAR(255),
    discard_reason VARCHAR(500),
    sending_lease_until TIMESTAMP,
    sending_lease_token VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_notification_submissions_notification_key UNIQUE (notification_key),
    CONSTRAINT notification_submissions_status_check CHECK (status IN ('PENDING', 'IN_FLIGHT', 'ACCEPTED', 'FAILED', 'DISCARDED')),
    CONSTRAINT notification_submissions_attempt_count_check CHECK (attempt_count >= 0)
);

CREATE INDEX idx_notification_submissions_status_created_at
    ON notification_submissions (status, created_at);
