CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    document VARCHAR(32) NOT NULL,
    document_type VARCHAR(8) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT customers_document_type_check CHECK (document_type IN ('CPF', 'RG', 'CNPJ', 'CNH')),
    CONSTRAINT customers_status_check CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE customer_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers (id),
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(32)
);

CREATE TABLE customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers (id),
    street VARCHAR(180) NOT NULL,
    number VARCHAR(40) NOT NULL,
    complement VARCHAR(120),
    neighborhood VARCHAR(120) NOT NULL,
    city VARCHAR(120) NOT NULL,
    state VARCHAR(60) NOT NULL,
    zip_code VARCHAR(20) NOT NULL,
    country VARCHAR(2) NOT NULL
);

CREATE INDEX idx_customer_contacts_customer_id ON customer_contacts (customer_id);
CREATE INDEX idx_customer_addresses_customer_id ON customer_addresses (customer_id);
