CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    recipient_email VARCHAR(254) NOT NULL,
    type VARCHAR(32) NOT NULL,
    channel VARCHAR(16) NOT NULL DEFAULT 'EMAIL',
    status VARCHAR(16) NOT NULL,
    subject VARCHAR(180) NOT NULL,
    body VARCHAR(2000) NOT NULL,
    reference_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,
    CONSTRAINT notifications_type_check CHECK (type IN ('ORDER_CONFIRMED', 'ORDER_PAYMENT_FAILED', 'ORDER_CANCELLED')),
    CONSTRAINT notifications_channel_check CHECK (channel IN ('EMAIL')),
    CONSTRAINT notifications_status_check CHECK (status IN ('SENT', 'FAILED')),
    CONSTRAINT fk_notifications_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE INDEX idx_notifications_customer_id ON notifications (customer_id);
