CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    recipient_email VARCHAR(254) NOT NULL,
    type VARCHAR(32) NOT NULL,
    channel VARCHAR(16) NOT NULL DEFAULT 'EMAIL',
    status VARCHAR(16) NOT NULL,
    subject VARCHAR(180) NOT NULL,
    body VARCHAR(2000) NOT NULL,
    reference_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,
    CONSTRAINT fk_notifications_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE INDEX idx_notifications_customer_id ON notifications (customer_id);
