CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT carts_status_check CHECK (status IN ('ACTIVE', 'CHECKED_OUT', 'ABANDONED')),
    CONSTRAINT fk_carts_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(220) NOT NULL,
    unit_price_amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'BRL',
    quantity INTEGER NOT NULL,
    CONSTRAINT cart_items_unit_price_amount_check CHECK (unit_price_amount >= 0),
    CONSTRAINT cart_items_quantity_check CHECK (quantity > 0),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id)
);

-- A customer may have at most one ACTIVE cart. This is enforced at the application/repository
-- level: CartJpaRepositoryAdapter.getOrCreateActiveByCustomerId() takes a `SELECT ... FOR UPDATE`
-- lock on the customer's own row (customers.id) before checking for / creating the ACTIVE cart,
-- so concurrent requests for the same customerId serialize instead of racing - portable locking
-- syntax, supported by both H2 and PostgreSQL. There is no database-level constraint enforcing
-- this directly on this table: a customer legitimately accumulates more than one CHECKED_OUT or
-- ABANDONED cart over time, and constraining only the ACTIVE rows portably (without PostgreSQL-
-- specific partial-index syntax) was judged not worth the added schema complexity here.
CREATE INDEX idx_carts_customer_id_status ON carts (customer_id, status);
CREATE INDEX idx_cart_items_cart_id ON cart_items (cart_id);
