CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    cart_id BIGINT NOT NULL,
    customer_name VARCHAR(220) NOT NULL,
    customer_document VARCHAR(64) NOT NULL,
    customer_document_type VARCHAR(32) NOT NULL,
    customer_email VARCHAR(320) NOT NULL,
    customer_phone VARCHAR(64),
    shipping_street VARCHAR(220) NOT NULL,
    shipping_number VARCHAR(32) NOT NULL,
    shipping_complement VARCHAR(220),
    shipping_neighborhood VARCHAR(220) NOT NULL,
    shipping_city VARCHAR(160) NOT NULL,
    shipping_state VARCHAR(80) NOT NULL,
    shipping_zip_code VARCHAR(32) NOT NULL,
    shipping_country VARCHAR(80) NOT NULL,
    status VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMP,
    CONSTRAINT orders_status_check CHECK (
        status IN ('WAITING_PAYMENT', 'PAYMENT_PROCESSING', 'PAYMENT_FAILED', 'CONFIRMED', 'CANCELLED')
    ),
    CONSTRAINT uq_orders_cart_id UNIQUE (cart_id),
    CONSTRAINT uq_orders_customer_idempotency_key UNIQUE (customer_id, idempotency_key),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_orders_cart FOREIGN KEY (cart_id) REFERENCES carts (id)
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(220) NOT NULL,
    unit_price_amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT order_items_unit_price_amount_check CHECK (unit_price_amount >= 0),
    CONSTRAINT order_items_quantity_check CHECK (quantity > 0),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE INDEX idx_orders_customer_created_at ON orders (customer_id, created_at, id);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);
