CREATE TABLE payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_reference VARCHAR(255) NOT NULL,
    reference_id VARCHAR(255) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(32) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    provider_transaction_id VARCHAR(255),
    idempotency_key VARCHAR(255) NOT NULL,
    authorization_fingerprint VARCHAR(64) NOT NULL,
    processing_lease_until TIMESTAMP,
    processing_lease_token VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT payment_attempts_amount_check CHECK (amount >= 0),
    CONSTRAINT uq_payment_attempts_attempt_reference UNIQUE (attempt_reference),
    CONSTRAINT uq_payment_attempts_reference_idempotency_key UNIQUE (reference_id, idempotency_key)
);

CREATE INDEX idx_payment_attempts_reference_id ON payment_attempts (reference_id);
